### PR TITLE
Updated CI builder image name as it was renamed.

### PR DESCRIPTION
**Pull request by AlexSkrypnyk**
https://github.com/integratedexperts/ci-builder

### CODE REVIEW

**Review by fubarhouse — APPROVED** [review]
Note the existing repository is redirecting from its source, and both images are available on Docker Hub.
* https://hub.docker.com/r/integratedexperts/circleci2-builder/
* https://hub.docker.com/r/integratedexperts/ci-builder/

On GitHub, note the redirection (as described a repository name change):
* https://github.com/integratedexperts/circleci2-builder
* https://github.com/integratedexperts/ci-builder

Impact of this change is exclusive to Circle CI config

**Comment by fubarhouse** [comment]
@alexdesignworks,

Is there any chance you can provide a link to the Circle CI build for your branch?

**Comment by AlexSkrypnyk** [comment]
@fubarhouse Latest build https://circleci.com/gh/govCMS/govCMS8/130 (it is a 'Details' link in the 'Checks' on GitHub UI)

Although both images are available on Dockerhub, only https://hub.docker.com/r/integratedexperts/ci-builder/ is going to be supported in the future. 

https://hub.docker.com/r/integratedexperts/circleci2-builder/ is still automatically published for backward compatibility.

**Comment by AlexSkrypnyk** [comment]
@fubarhouse  The build failed.  Could you please re-run it from CI (I do not have the permission to re-run).

**Comment by pandaskii** [comment]
Merged, thanks

**Pull request merged**
