### PR TITLE
Add weitzman/drupal-test-traits and mockery/mockery

### PR DESCRIPTION
**Pull request by simesy**
I use these sometimes for writing unit tests, and it would be beneficial to have them available.

### CODE REVIEW

**Review by sonnykt — APPROVED** [review]

**Comment by pandaskii** [comment]
@simesy 

Do we need to update https://github.com/govCMS/govCMS8/blob/1.x/tests/composer.json as well?

This is a good start point so we can add more tests into CI for distribution and give agencies the ability to write test cases for the site requirements.

Also is it possible to put an example of a test case?

thanks

**Comment by simesy** [comment]
I don't know why tests/composer.json exists, but this PR would go into https://github.com/govCMS/require-dev now

**Comment by pandaskii** [comment]
@simesy thanks, are you good for me to close this PR in favour of the PR goes into another project?

**Comment by simesy** [comment]
I can :)

**Pull request closed without merging**
