### PR TITLE
[GOVCMSD8-261] [8.x-1.x] Update drupal/ctools to 3.2.0 (from 8.x-3.0) 

### PR DESCRIPTION
**Pull request by suhyeonh**
### https://www.drupal.org/project/ctools/releases/8.x-3.2
Release notes
Changes since 8.x-3.1:

#3033634 by manuel.adan: Replace user temp store service name by the core temp store in forms
#3033299 by thalles: Standards on Form/ExampleConfigEntityExternalForm
#3033651 by manuel.adan: AJAX forms broken after URL refactoring, string expected instead of object
#3033116 by Mithun S: Update Dependencies Format in .info.yml

### CODE REVIEW

**Review by gargsuchi — DISMISSED** [review]

**Review by fubarhouse — CHANGES_REQUESTED** [review]
Could you please also ensure `composer.json` is also updated?

**Review by fubarhouse — DISMISSED** [review]
Excellent thanks 😄

**Comment by tobybellwood** [comment]
Can we make sure that we're across https://www.drupal.org/project/panels/issues/3031778 first (TL;DR - 3.0 works, Panels has a patch for 3.2)

How does ctools get in there in the first place - I presume as a dependency?

**Comment by fubarhouse** [comment]
This is dependent on the following patch making it into panels:
* https://www.drupal.org/project/panels/issues/3031778

As the patch has not been merged, it will be removed from the coming release.
Until then, a new patch with the change from 932ced6 will need a new PR for the coming release.

**Review by tobybellwood — CHANGES_REQUESTED** [review]
This is a blocking review until patch merged

**Review by pandaskii — CHANGES_REQUESTED** [review]
Please resolve the conflicts in PR

**Comment by tobybellwood** [comment]
https://www.drupal.org/project/panels/releases/8.x-4.4 has fixed the linked patch

It seems there is a related issue in panelizer https://www.drupal.org/project/panelizer/issues/3034080

**Pull request merged**
