### PR TITLE
Release 1.0-beta1

### PR DESCRIPTION
**Pull request by fubarhouse**
This is a roll-up merge for the 1.0-beta1 release milestone which resolves and merges the following:

* #186 [GOVCMSD8-100] Apply GA patch for internal tracking bug fix
* #198 Provide a list of default permissions allowed for site admins 
* #197 Drupal core updates to v8.6.5 
* #200 Update Drupal core to 8.6.6
* #201 Updates Drupal core to 8.6.7
* #195 Update user.role.site_administrator.yml 
* #193 Update drupal/webform to 5.1 
* #192 Update drupal/jsonapi to 2.0
* #191 Update drupal/linkit to 5.0-beta8
* #190 Update drupal/environment_indicator to 3.5 
* #189 Update drupal/config_update to 1.6 
* #188 Update drupal/consumers to 1.4 
* #176 GovCMS 118 - Remote video
* #178 Update drupal/simple_oauth to 3.11 
* #177 Update drupal/search_api to 1.11
* #175 Updated CI builder image name as it was renamed. 
* #166 165 update edgy layout config 
* #130 Fix parallax position in Edge 17.
* #161 Fix Styleguide link 404
* #133 GovCMS 132 – Simplify Panelizer uninstall
* #174 Update permissions_by_term to 2.6
* #173 Update drupal/facets to 1.2 
* #172 Update drupal/ds to 3.2
* #171 Update drupal/config_filter to 1.4

### CODE REVIEW

**Review by gargsuchi — APPROVED** [review]

**Comment by gargsuchi** [comment]
@fubarhouse  Do we need both #200 and #201 in here? Should we not close #200?

**Comment by fubarhouse** [comment]
Because of timing of these events, #200 and #197 were already been merged into this branch.

This can be noted towards the bottom of this page as the merge commits and commits were pushed.

**Comment by gargsuchi** [comment]
ok.

**Comment by pandaskii** [comment]
thanks

**Pull request closed without merging**
