### PR TITLE
Fix parallax position in Edge 17.

### PR DESCRIPTION
**Pull request by honzapara**
The latest Edge (17) breaks the positioning of the parallax caused by negative z-index. Setting z-index to 0 fixes the issue.

### CODE REVIEW

**Review by kybersoft — APPROVED** [review]
All looks good, this should be merged with a high priority.

**Comment by tobybellwood** [comment]
Hi @honzapara - I've given it a whirl, and I'm getting a weird grey blocking effect, even with the zIndex at 0

`Microsoft Edge 42.17134.1.0`
`Microsoft EdgeHTML 17.17134`

image

**Comment by honzapara** [comment]
Hi @tobybellwood, the fix with z-index was not enough for this issue. Final solution is to update library from 1.10.3 to 1.10.6 where they are implementing fix for the Edge and IE. The trick is with opacity: 0.9999 which somehow changes the context of z-index.

**Review by tobybellwood — APPROVED** [review]
LGTM - update to Jarallax 1.10.6 fixed the issue.

**Comment by kybersoft** [comment]
Thank you @honzapara and @tobybellwood , nice to see PR is now ready to be merged.

**Comment by pandaskii** [comment]
Merged, thanks

**Pull request merged**
