### PR TITLE
[GOVCMSD8-100] Apply GA patch for internal tracking bug fix

### PR DESCRIPTION
**Pull request by fubarhouse**
Drupal core search when configured to track internal use is causing some errors due to a bug.
This patch will at least for now remediate this bug which includes business impact.

### CODE REVIEW

**Review by gargsuchi — APPROVED** [review]
Approving the PR - even though the d.o issue says that the patch needs tests.

**Comment by fubarhouse** [comment]
@pandaskii and @ruwanl have determined this is important enough to be included in the first beta.

**Comment by fubarhouse** [comment]
Tested by me successfully as part of #199

**Comment by fubarhouse** [comment]
> Hi @fubarhouse,
> just thinking if this patch is generaly needed. And if so should that be included in the composer.json as well?

We've opened #256 to address this - my apologies for not seeing this sooner.

**Pull request merged**
