### PR TITLE
Drupal core updates to v8.6.5

### PR DESCRIPTION
**Pull request by fubarhouse**
PR for #196 to update the Drupal core.

### CODE REVIEW

**Review by gargsuchi — APPROVED** [review]

**Comment by fubarhouse** [comment]
Suchi,

As discussed, assigning to you.

**Review by pandaskii — COMMENTED** [review]
Regarding govcms/govcms in composer-lagoon.json, shall we fix the version number as well?

@fubarhouse @ruwanl @srowlands 

PR itself looks good 👍

**Review by pandaskii — COMMENTED** [review]
Shall we close it in favour of PR #201

**Comment by fubarhouse** [comment]
Sounds good!

**Pull request closed without merging**
