### PR TITLE
[GOVCMSD8-545] Update Entity Class Formatter module from 1.1 to 1.3.

### PR DESCRIPTION
**Pull request by honzapara**
Hi GovCMS,

We would like to update our Entity Class Formatter contrib module. This change doesn't affect GovCMS profile and its sub-modules. We need this update so the Entity Class Formatter works properly with Layout Builder.

Thank you.

### CODE REVIEW

**Comment by Belhendo** [comment]
Thanks @honzapara, we will review internally and let you know.

**Review by pandaskii — DISMISSED** [review]
Looks good. Happy to merge it after testing.

Thanks for the contribution

**Comment by murraywoodman** [comment]
Hi @pandaskii I'm not sure what is going on with the Beta10 Release 7 days ago. Maybe that was added by mistake. Can we expect this code to go into 1.2?

**Comment by tobybellwood** [comment]
whilst you're here @murraywoodman - how are you going with making your various modules D9 compatible - our last check indicated you need to:
`Add core_version_requirement: ^8 || ^9 to entity_class_formatter.info.yml to designate that the module is compatible with Drupal 9`

**Comment by murraywoodman** [comment]
Never fear. We are on the case @tobybellwood . We are making a new release of the module in the next week or so. There will be a couple of new features and the D9 compatibility too.

**Comment by kybersoft** [comment]
@tobybellwood Done. Now it's your turn ;-)

Feel free to update to the recent version instead:
- https://www.drupal.org/project/entity_class_formatter/releases/8.x-1.3

**Comment by murraywoodman** [comment]
So 1.3 is out . Given that is has D9 compatibility it would be good to get it in. Would you like an update to this branch?

**Comment by tobybellwood** [comment]
I'll find out where we're up to with testing.  I can always `s/1.2/1.3` if needed :-)

**Comment by murraywoodman** [comment]
We now have a layout builder based site which is ready to go live. We do need the 1.3 version of the module to be deployed so that the site will function properly. Without the update, the editor selected options will not work, resulting in a bad editor experience. Please take a look at this as soon as possible so that we can reliably use layout builder in our GovCMS8 projects.

**Comment by kybersoft** [comment]
Hi @honzapara , could you please change the version from 1.2 to 1.3, so @tobybellwood could merge that? These updates are not breaking anything on existing sites - they are adding new features to support Layout Builder. Thank you.

**Comment by honzapara** [comment]
Based on @kybersoft request, I'm updating Entity Class Formatter to 1.3 version.

@pandaskii or  @kybersoft can you please do the review again?

**Review by kybersoft — DISMISSED** [review]

**Review by kybersoft — APPROVED** [review]

**Comment by honzapara** [comment]
Due to the merge conflict, I had to solve it (drupal-org.make is no longer part of the repo) and push it again.
@kybersoft please review again. Thanks.

**Comment by murraywoodman** [comment]
Thanks guys!

**Pull request merged**
