### PR TITLE
[GOVCMSD8-263] Added devel

### PR DESCRIPTION
**Pull request by gargsuchi**
Added devel to drupal-org.make. Moved devel from require-dev to require in composer.json.
Also fixed 
* Travis fails
* composer depracation warning

**https://www.drupal.org/project/devel/releases/8.x-2.0**

Release notes
Issue #3005475 by lussoluca: Remove Execute PHP feature
Issue #2914657 by lussoluca: Cannot use object of type Closure as array
Issue #3003353 by Stacie_A: Capitalize the Devel Generate module name.
Issue #2987782 by lussoluca: Add the Symfony var-dumper component as a dependency
Issue #2999892 by guillermo-simeon: function dd is already defined in symfony since Drupal 8.6
Issue #3001202 by stefan.korn: Devel tests are failing
Issue #2987140 by volkswagenchick: Fix README, useful links and formatting.
Issue #2847714: Compatibility with big pipe
Issue #2986099 by volkswagenchick, daggerhart: Webprofiler submodule - typo in UI
Issue #2866135 by webflo: Exception when web profiler module enabled
Issue #2957193 by drclaw: Webprofiler reports views profiling times as milliseconds, but they are seconds
Issue #2897792 by lussoluca: Warning Illegal string offset ‘status_code’ and ‘status_text’ on database profiler page
Issue #2951821 by salvis, Chi, rajeshwari10: Fix warning: count(): Parameter must be an array.
Issue #2927963 by kalpaitch: getInstance() fatals on MailManagerWrapper
Issue #2948701 by mxr576: Do not override on_stats callback
Issue #2962196 by joelpittet: Migration page throws Error when webprofiler is installed
Issue #2895745 by luca_cracco: Missing proxy class for lazy service ‘webprofiler.list’
Issue #2448063 by jacob.embree, zaporylie: Add #actions container to submit buttons
Issue #2951505 by tormi: Fix outdated link to hook_page_alter() in settings page.
Issue #2933092 by GeduR, dhwani.addweb: PHPCS Dependencies prefix info.yml
Issue #2944180 by jeqq: Set the correct path alias langcode when generating nodes with aliases
Issue #2933100 by GeduR: Wrong variable $node instead of $account in ExampleDevelGenerate.php
Issue #2933101 by GeduR: Remove empty devel_generate_example.module file
Issue #2933169 by GeduR, willzyx: DevelDumperManager dependency injection integration
Issue #2935906 by ckaotik: Session might not exist for rebuild theme registry warning
Issue #2933312 by DuaelFr: devel_generate should have an extra.drush.services section in its composer.json
Issue #2931229 by martin107: Branch blocker DevelTwigExtensionTest is broken

### CODE REVIEW

**Comment by gargsuchi** [comment]
We might need to look into this https://www.drupal.org/project/admin_toolbar/issues/3009193

**Review by courdo1 — APPROVED** [review]
Reviewed and tested

**Comment by tobybellwood** [comment]
How do we ensure that devel isn't running in prod - are there drutiny tests, or should we disable in production.settings.php?

**Comment by fubarhouse** [comment]
Just had a check and there are no Drutiny audits for making sure Devel is disabled.

Let me know if you'd like this to be done.

**Comment by Feng-Shui** [comment]
Now that Execute PHP is remove from devel, is there any reason not to allow it to run in prod?  It provides some useful things for site admins, being able to devel view nodes in particular is really useful.

**Comment by tobybellwood** [comment]
Thanks @Feng-Shui - noting that PHP has been removed (in https://git.drupalcode.org/project/devel/commit/7eb4b0c10f5f3b1bddf20d1ac907b04e1afde17d), I'd have less concerns about this being enabled in prod.

https://www.drupal.org/project/devel/releases/8.x-2.1 was released last week - and this PR should be updated to reflect that

**Pull request merged**
