### PR TITLE
Remove drupal-org-core.make and drupal-org.make file

### PR DESCRIPTION
**Pull request by mingsong-hu**

### CODE REVIEW

**Review by ruwanl — DISMISSED** [review]

**Comment by tobybellwood** [comment]
If we're removing these, we can also remove the composer package tooling that creates them

**Comment by mingsong-hu** [comment]
> If we're removing these, we can also remove the composer package tooling that creates them

Remove the src/Composer/Package.php file and update the composer.json file to remove the sections we don't need anymore.
Please let me know if I miss something.

**Comment by tobybellwood** [comment]
yup - it should just be removing the src/composer/package.php file, relevant scripts and calls in composer.json - and maybe also src/iniencoder.php may not be used anywhere else?

**Comment by mingsong-hu** [comment]
> yup - it should just be removing the src/composer/package.php file, relevant scripts and calls in composer.json - and maybe also src/iniencoder.php may not be used anywhere else?

As far as I see, /src/iniencoder.php is only used in /src/Composer/Package.php. As we are removing the Package.php, I think we need to remove iniencoder.php too.

**Review by tobybellwood — APPROVED** [review]
LGTM - nice to get rid of the package stuff - it was always out of date!

**Pull request merged**
