### PR TITLE
Update drupal/panels to 4.4.0

### PR DESCRIPTION
**Pull request by pandaskii**
https://www.drupal.org/project/panels/releases/8.x-4.4

**Release notes**
This is a incremental release containing compatibility fixes with Drupal core

Changes since 8.x-4.3:

- Issue #3031778 by iyyappan.govind, YurkinPark, skhanbwm, nickolaj, thalles: Change panels store.
- Issue #2862959 by antroxim, mohit_aghera, chrishks: JS error in IPE - Cannot read property 'top' of undefined

### CODE REVIEW

**Review by gargsuchi — DISMISSED** [review]
@pandaskii  Why are you putting 4.4.0 and not 4.4?

**Comment by pandaskii** [comment]
> @pandaskii Why are you putting 4.4.0 and not 4.4?

This is advised by Drupal.org https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies

```composer require 'drupal/<modulename>:<version>'```

For example:
```
composer require 'drupal/token:^1.5'
composer require 'drupal/simple_fb_connect:~3.0'
composer require 'drupal/ctools:3.0.0-alpha26'
composer require 'drupal/token:1.x-dev'
```

**Comment by gargsuchi** [comment]
@pandaskii 
Based on your comment above, it should be  "drupal/panels": "4.4" and not  "drupal/panels": "4.4.0"

 "drupal/panels": "4.4.0" - this will work, I am not denying it. But we should stick to the best practices and format followed up for all the other modules.

**Comment by pandaskii** [comment]
> @pandaskii
> Based on your comment above, it should be "drupal/panels": "4.4" and not "drupal/panels": "4.4.0"
> 
> "drupal/panels": "4.4.0" - this will work, I am not denying it. But we should stick to the best practices and format followed up for all the other modules.

composer require 'drupal/ctools:3.0.0-alpha26' ???

**Comment by tobybellwood** [comment]
acknowledging that there are inconsistencies within our composer.json, we should pick a method and stick with it.  In order to make Drupal as future-proof as possible, and compliant within the wider composer/packagist ecosystem, I agree with @pandaskii  that we should use the suggested syntax wherever possible

`{major}.{minor}.0-{stability}{#}`

Please limit public reviews to the content of the PR, or suggesting additions (e.g. config changes).

We won't be going back and changing (the naming convention) of modules we've already added, but we should be more aware of the conventions going forwards.

**Review by gargsuchi — APPROVED** [review]

**Review by ruwanl — APPROVED** [review]

**Pull request merged**
